FROM python:3.9-slim

WORKDIR /app

# Kopiowanie plików requirements
COPY requirements.txt .

# Instalacja zależności
RUN pip install --no-cache-dir -r requirements.txt

# Kopiowanie aplikacji
COPY producer.py .
COPY btceur.csv .

# Skrypt startowy z oczekiwaniem na Kafkę
COPY wait-for-kafka.sh .
RUN chmod +x wait-for-kafka.sh

EXPOSE 5001

# Uruchomienie z oczekiwaniem na Kafkę
CMD ["./wait-for-kafka.sh", "kafka:29092", "--", "python", "producer.py"]